# Generated by Django 4.2.5 on 2023-09-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproviderpersonalinfo',
            old_name='firtName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='serviceproviderpersonalinfo',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='serviceproviderpersonalinfo',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='serviceproviderworkinfo',
            name='yearsOfExperince',
        ),
        migrations.AddField(
            model_name='serviceproviderpersonalinfo',
            name='phone_number',
            field=models.CharField(default='(+254) 000-0000', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceproviderworkinfo',
            name='years_of_experince',
            field=models.IntegerField(default=0),
        ),
    ]
