# Generated by Django 4.2.5 on 2023-09-25 18:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_firtname_serviceproviderpersonalinfo_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderworkinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='serviceproviderworkinfo',
            name='personal_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.serviceproviderpersonalinfo'),
        ),
        migrations.AlterField(
            model_name='serviceproviderpersonalinfo',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='First name must be at least 3 characters.')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderpersonalinfo',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Last name must be at least 3 characters.')]),
        ),
    ]
