# Generated by Django 4.2.5 on 2023-09-27 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_serviceproviderworkinfo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproviderworkinfo',
            old_name='years_of_experince',
            new_name='years_of_experience',
        ),
        migrations.AddField(
            model_name='serviceproviderpersonalinfo',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceproviderpersonalinfo',
            name='Update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceproviderpersonalinfo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serviceproviderworkinfo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
