# Generated by Django 4.1.5 on 2023-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_years_of_experince_serviceproviderworkinfo_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderpersonalinfo',
            name='Id_number',
            field=models.CharField(default='000-000-00', max_length=10),
        ),
    ]
