# Generated by Django 4.2.6 on 2023-10-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_serviceproviderpersonalinfo_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderpersonalinfo',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='photos/'),
        ),
    ]
