# Generated by Django 4.2.6 on 2023-10-25 05:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_requestservice_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='First name must be at least 3 characters.')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Last name must be at least 3 characters.')])),
                ('phone_number', models.CharField(default='(+254) 000-0000', max_length=50)),
                ('Id_number', models.CharField(default='000-000-00', max_length=10)),
                ('Active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(default='default_photo.jpg', upload_to='photos/')),
            ],
        ),
    ]
