# Generated by Django 4.2.6 on 2023-10-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_clientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderworkinfo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
