# Generated by Django 4.2.6 on 2023-10-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_serviceproviderworkinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderpersonalinfo',
            name='Active',
        ),
        migrations.AddField(
            model_name='serviceproviderworkinfo',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
