# Generated by Django 4.2.6 on 2023-10-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_serviceproviderpersonalinfo_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderworkinfo',
            name='Active',
        ),
    ]
